<?xml version="1.0"?>
<package format="3">
  <name>emc270_icr_estimator</name>
  <version>0.1.0</version>
  <description>Fast and robust online ICR estimation for EMC-270 and PandarXT.</description>
  <maintainer email="maintainer@example.invalid">EMC-270 ICR maintainers</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>diagnostic_msgs</depend>
  <depend>diagnostic_updater</depend>
  <depend>eigen</depend>
  <depend>emc270_icr_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
