- direction: GZ_TO_ROS
  gz_topic_name: /clock
  gz_type_name: gz.msgs.Clock
  ros_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
- direction: ROS_TO_GZ
  gz_topic_name: /model/gouda/cmd_vel
  gz_type_name: gz.msgs.Twist
  ros_topic_name: /sim/cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
- direction: GZ_TO_ROS
  gz_topic_name: /model/gouda/ground_truth
  gz_type_name: gz.msgs.Odometry
  ros_topic_name: /sim/odometry
  ros_type_name: nav_msgs/msg/Odometry
- direction: GZ_TO_ROS
  gz_topic_name: /gouda/imu
  gz_type_name: gz.msgs.IMU
  ros_topic_name: /sim/imu
  ros_type_name: sensor_msgs/msg/Imu
- direction: GZ_TO_ROS
  gz_topic_name: /gouda/lidar/points
  gz_type_name: gz.msgs.PointCloudPacked
  ros_topic_name: /sim/points
  ros_type_name: sensor_msgs/msg/PointCloud2
