const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const network=[];page.on('request',r=>network.push(new URL(r.url()).pathname));
 await page.goto('http://127.0.0.1:8766');
 await page.waitForFunction(()=>document.querySelector('#connection').textContent.includes('接続中'),null,{timeout:30000});
 await page.waitForFunction(()=>document.querySelector('#rviz-status').textContent.includes('RViz2 起動中'),null,{timeout:60000});
 assert.equal(await page.locator('#view-3d').count(),0);
 assert.equal(await page.locator('#native-screen').count(),0);
 assert.equal(await page.locator('#map').count(),1);
 assert.ok(await page.locator('#map').evaluate(c=>c.width>0));
 const state=await page.request.get('http://127.0.0.1:8766/api/state').then(r=>r.json());
 assert.equal(state.mode,'live');assert.equal(state.observation_only,true);
 assert.equal(state.pose,null);assert.equal(state.map,null);assert.equal(state.mapping_frames,0);
 assert.ok(await page.locator('#mapping-start').isDisabled());
 await page.locator('#tab-planning').click();
 assert.ok(await page.locator('#tool-start').isVisible());
 assert.ok(await page.locator('#plan').isDisabled());
 assert.match(await page.locator('#plan-summary').textContent(),/計画開始位置/);
 assert.match(await page.locator('#plan-summary').textContent(),/保存地図/);
 await page.locator('#tab-mapping').click();
 const viewer=await page.request.get('http://127.0.0.1:8766/api/viewer').then(r=>r.json());
 assert.equal(viewer.available,true);assert.ok(viewer.pid);
 assert.equal((await page.request.get('http://127.0.0.1:8766/native/ws')).status(),404);
 assert.equal((await page.request.get('http://127.0.0.1:8766/native/vendor/core/rfb.js')).status(),404);
 for(let i=0;i<3;i++){await page.locator('#tab-planning').click();await page.locator('#tab-mapping').click();}
 await page.reload();
 await page.waitForFunction(()=>document.querySelector('#rviz-status').textContent.includes('RViz2 起動中'),null,{timeout:15000});
 assert.equal((await page.request.get('http://127.0.0.1:8766/api/state',{headers:{Origin:'http://untrusted.invalid'}})).status(),403);
 assert.equal((await page.request.get('http://127.0.0.1:8766/api/unknown')).status(),404);
 assert.equal(network.some(p=>p.startsWith('/native/')),false);
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: separate RViz, no browser transfer, retained 2D operations, API guards');
})().catch(e=>{console.error(e);process.exit(1)});
