[env:dualsense]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
platform_packages =
    framework-arduinoespressif32 @ https://github.com/ricardoquesada/esp32-arduino-lib-builder/releases/download/4.1.0/esp32-bluepad32-4.1.0.zip
monitor_speed = 115200
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = huge_app.csv
monitor_dtr = 0
monitor_rts = 0
