[env:gouda_esp32]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = huge_app.csv
monitor_dtr = 0
monitor_rts = 0
build_unflags = -std=gnu++11
build_flags = -Wall -Wextra -std=gnu++17
