"""Identity check between two intent.md versions for the lines of given requirements.

Reports, per requirement, the line number in each version, the SHA-256 of the
line text in each version and whether they are identical, plus the whole-file
diff. Requirement texts come from the model (sources of kind intent_lines).
Deterministic; writes a Markdown and a JSON report.
"""
import argparse, difflib, hashlib, json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_model import load_yaml, DESIGN, ROOT  # noqa: E402


def sha(s): return hashlib.sha256(s.encode()).hexdigest()


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--old', default='design/baselines/intent_history/intent_v3_f0df295f9927.md')
    p.add_argument('--new', default='design/intent.md')
    p.add_argument('--requirements', default='RQ-I023,RQ-I024,RQ-I025,RQ-I026,RQ-I027,RQ-I062,RQ-I063,RQ-I064,RQ-I065,RQ-I066,RQ-I067,RQ-I068,RQ-I069')
    p.add_argument('--out', default='design/reports/intent_identity')
    a = p.parse_args()
    m = load_yaml(DESIGN / 'model.yaml'); srcs = {s['id']: s for s in m['sources']}; ents = {e['id']: e for e in m['entities']}
    old_p, new_p = ROOT / a.old, ROOT / a.new
    old = old_p.read_text().splitlines(); new = new_p.read_text().splitlines()
    # A requirement line may be replaced only by a recorded human edit: adoption=superseded, a resolved_by_intent
    # reconciliation naming the successor, and an authority revision with a decision_ref whose removed/added lines
    # contain the old and new text. Such a row is reported as 置換 (not identical, but recorded). Anything else fails.
    recons = [e for e in m['entities'] if e['kind'] == 'reconciliation' and e['reconciliation']['state'] == 'resolved_by_intent']
    ars = m.get('authority_revisions', [])
    def recorded_successor(rq, text):
        if ents[rq]['adoption'] != 'superseded': return None
        for c in recons:
            if rq in c['reconciliation']['affected_refs']:
                for succ in c['reconciliation']['adopted_requirement_refs']:
                    if succ == rq or ents[succ]['adoption'] == 'superseded': continue
                    stext = srcs[ents[succ]['source_refs'][0]]['raw_fields']['text']
                    for ar in ars:
                        if ar.get('decision_ref') and any(l['text'] == text for l in ar['removed_lines']) and any(l['text'] == stext for l in ar['added_lines']):
                            return dict(successor=succ, text=stext, reconciliation=c['id'], authority_revision=ar['id'], decision=ar['decision_ref'])
        return None
    rows = []; ok = True
    for rq in a.requirements.split(','):
        text = srcs[ents[rq]['source_refs'][0]]['raw_fields']['text']
        lo = [i for i, l in enumerate(old, 1) if l == text]; ln = [i for i, l in enumerate(new, 1) if l == text]
        same = bool(lo) and bool(ln) and sha(old[lo[0] - 1]) == sha(new[ln[0] - 1])
        rep = None if same else recorded_successor(rq, text)
        if rep:
            ls = [i for i, l in enumerate(new, 1) if l == rep['text']]
            rep['new_line'] = ls[0] if ls else None
            if not ls: rep = None
        ok &= same or bool(rep)
        rows.append(dict(requirement=rq, text=text, old_line=lo[0] if lo else None, new_line=ln[0] if ln else None,
                         old_sha256=sha(old[lo[0] - 1]) if lo else None, new_sha256=sha(new[ln[0] - 1]) if ln else None, identical=same,
                         replacement=rep))
    diff = list(difflib.unified_diff(old, new, fromfile=str(a.old), tofile=str(a.new), lineterm='', n=0))
    report = dict(old_file=a.old, old_sha256=hashlib.sha256(old_p.read_bytes()).hexdigest(), new_file=a.new, new_sha256=hashlib.sha256(new_p.read_bytes()).hexdigest(),
                  all_identical=ok, rows=rows, unified_diff=diff)
    Path(a.out + '.json').write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n')
    lines = ['# GENERATED by design/tools/check_intent_identity.py — do not edit.', '', f"# intent.md 版間の同一性確認（{Path(a.old).name} → {Path(a.new).name}）", '',
             f"旧版 SHA-256 `{report['old_sha256']}`、新版 SHA-256 `{report['new_sha256']}`。対象行の結果: **{'すべて一致' if all(r['identical'] for r in rows) else ('一致または記録済みの置換のみ' if ok else '未記録の不一致あり')}**。置換は、人の編集として authority_revision（decision_ref 付き）と reconciliation に記録されたものだけを認める。", '',
             '| 要求 | 旧版の行 | 新版の行 | 旧版の行 SHA-256 | 新版の行 SHA-256 | 一致 |', '|---|---:|---:|---|---|---|']
    for r in rows:
        rep = r.get('replacement')
        verdict = '一致' if r['identical'] else (f"置換（記録済み: {rep['successor']} 新版 {rep['new_line']} 行、{rep['reconciliation']}・{rep['authority_revision']}・{rep['decision']}）" if rep else '**不一致（未記録）**')
        lines.append(f"| {r['requirement']} | {r['old_line']} | {r['new_line']} | {(r['old_sha256'] or '-')[:16]}… | {(r['new_sha256'] or '-')[:16]}… | {verdict} |")
    lines += ['', '## 全体差分（unified diff, n=0）', '', '```diff'] + diff + ['```', '']
    Path(a.out + '.md').write_text('\n'.join(lines))
    nrep = sum(1 for r in rows if r.get('replacement'))
    print(('identical' if nrep == 0 else f'identical-or-recorded-replacement ({nrep} replaced)') if ok else 'DIFFERENT (unrecorded)', len(rows), 'requirements;', sum(1 for d in diff if d.startswith(('+', '-')) and not d.startswith(('+++', '---'))), 'diff lines')
    return 0 if ok else 1


if __name__ == '__main__': sys.exit(main())
