"""Generate declarative configuration from the canonical model (RQ-I076).

Reads every parameter entity that declares where it is applied
(`parameter.declaration`) and writes, deterministically:

  design/generated/params/<target>.yaml   ROS 2 parameter files (one per target node), only
                                           values whose state is approved or source_value;
                                           unresolved keys are listed in a comment block as tbd
  design/generated/params/firmware_config.yaml   firmware settings (same rule)
  design/generated/params/bt_params.yaml         values to substitute into BT XML
  design/generated/params/index.json             provenance: PRM id, key, state, target, timing, sha of model

Nothing here is a vehicle-approved value unless value_state is approved.
Hand editing is forbidden; change the model through a revision instead.
"""
import hashlib, json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_model import load_yaml, DESIGN  # noqa: E402

OUT = DESIGN / 'generated' / 'params'
HEADER = '# GENERATED by design/tools/generate_params.py from design/model.yaml — do not edit; change the model via a revision.\n'


def render(model):
    """Return {relative filename: text}. Pure function of the model, so checks can compare."""
    params = [e for e in model['entities'] if e['kind'] == 'parameter' and e['parameter'].get('declaration') not in (None, 'code_state_machine', 'model_declared')]
    groups = {}
    for e in params:
        p = e['parameter']
        fname = 'firmware_config.yaml' if p['declaration'] == 'firmware_config' else 'bt_params.yaml' if p['declaration'] == 'bt_xml' else f"{p['target']}.yaml"
        groups.setdefault(fname, []).append(e)
    files = {}; index = []
    msha = hashlib.sha256(json.dumps(model['entities'], sort_keys=True, ensure_ascii=False, default=str).encode()).hexdigest()
    for fname in sorted(groups):
        ents = sorted(groups[fname], key=lambda e: e['id'])
        lines = [HEADER, f'# source model entities sha256: {msha[:16]}', '']
        decided = [e for e in ents if e['parameter']['value_state'] in ('approved', 'source_value')]
        tbd = [e for e in ents if e['parameter']['value_state'] == 'unresolved']
        if fname not in ('firmware_config.yaml', 'bt_params.yaml'):
            lines.append(f"{ents[0]['parameter']['target']}:")
            # An empty mapping must stay a valid ROS 2 parameter file (a bare "ros__parameters:" would parse as null).
            lines.append('  ros__parameters:' + (' {}' if not decided else ''))
            indent = '    '
        else:
            indent = ''
        for e in decided:
            p = e['parameter']
            v = p['value']
            vs = json.dumps(v, ensure_ascii=False) if not isinstance(v, bool) else str(v).lower()
            lines.append(f"{indent}{p['param_key']}: {vs}  # {e['id']} {p['value_state']} unit={p['unit']} apply={p['apply_timing']}{' (記載値。実測未)' if p['value_state'] == 'source_value' else ''}")
        if tbd:
            lines.append(f"{indent}# tbd（未確定。値は入れない。一般値で補わない）:")
            for e in tbd:
                p = e['parameter']
                lines.append(f"{indent}#   {p['param_key']}  {e['id']} unit={p['unit']} issues={','.join(e['issue_refs'])}")
        files[fname] = '\n'.join(lines) + '\n'
        for e in ents:
            p = e['parameter']
            index.append(dict(id=e['id'], file=fname, key=p['param_key'], target=p['target'], declaration=p['declaration'], apply_timing=p['apply_timing'], value_type=p.get('value_type'), value_state=p['value_state'], value=p['value'] if p['value_state'] != 'unresolved' else None, unit=p['unit']))
    files['index.json'] = json.dumps(dict(model_entities_sha256=msha, parameters=index), ensure_ascii=False, indent=2) + '\n'
    return files


def main():
    model = load_yaml(DESIGN / 'model.yaml')
    files = render(model)
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob('*'):
        if old.name not in files: old.unlink()
    for name, text in files.items(): (OUT / name).write_text(text)
    print('generated', sorted(files))


if __name__ == '__main__': main()
