"""Render review views from the canonical model. Deterministic; no hand edits downstream.

Outputs (all derived, never the source of truth):
  design/generated/gate3_review_C001_C013.md   intent quote / replaced range / retained range / current handling
  design/generated/impact_estop.md             term search over Excel + drawio extraction, joined with model handling
  design/generated/lower_design_r2.md          modes, transitions, state owners, node split, major IFs (案)
  design/generated/human_decisions_r2.md       up to 10 human decisions ordered by affected-ID count
  design/conflicts.yaml                        reconciliation ledger view (requested path; generated)
  design/intent_open_items.yaml                open/pending items touching intent requirements (requested path; generated)
  design/intent_index.yaml                     intent line -> requirement ID -> referencing entities (requested path; generated)
  design/reports/model_diff_r2.md              baseline vs current model difference summary
  design/generated/stop_resume_conditions.md   per transition: old-goal termination, human pause/end retention, neutralisation owner (DEC-056)
  design/generated/failure_modes.md            failure modes derived from transitions/parameters with transition and test references (DEC-056)
"""
import collections, json, re, sys
from pathlib import Path
from ruamel.yaml import YAML
sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_model import load_yaml, canonical, current_line_map, DESIGN, ROOT, EXTRACT, BASELINE  # noqa: E402

GEN = DESIGN / 'generated'
ESTOP_TERMS = ['非常停止', '非常押し', 'E-stop', 'Estop', 'emergency', 'Emergency', '押下検知', '緊急停止', '緊急']
HEADER = '# GENERATED by design/tools/render_views.py from design/model.yaml — do not edit; edit the model via a revision change set.\n'


def esc(s): return str(s).replace('|', '\\|').replace('\n', '<br>')


def main():
    m = load_yaml(DESIGN / 'model.yaml'); manifest = json.loads((DESIGN / 'migration_manifest.json').read_text())
    design_check = json.loads((DESIGN / 'reports/design_check.json').read_text())
    ents = {e['id']: e for e in m['entities']}; srcs = {s['id']: s for s in m['sources']}
    decisions = {d['id']: d for d in m.get('decisions', [])}
    linemap = current_line_map(m)
    rq_line = {v: k for k, v in linemap.items()}
    for e in m['entities']:  # superseded requirement texts: show their version's line
        if e['kind'] == 'requirement' and e['id'] not in rq_line and srcs[e['source_refs'][0]]['kind'] == 'intent_lines': rq_line[e['id']] = f"{srcs[e['source_refs'][0]]['file_ref']}:{srcs[e['source_refs'][0]]['locator']['line_start']}"

    def rqtext(rq): return srcs[ents[rq]['source_refs'][0]]['raw_fields']['text']
    def pos(sid):
        s = srcs[sid]; l = s['locator']
        if s['kind'] == 'excel_row': return f"Excel {l['sheet']}!{l['range']}"
        if s['kind'] == 'intent_lines': return f"intent.md:{l['line_start']}"
        return f"drawio {l['element_id']}"
    def refs(ids): return ', '.join(f'`{i}`' for i in ids)
    GEN.mkdir(exist_ok=True)

    # ---------------- gate 3 review table ----------------
    lines = [HEADER, '# ゲート3レビュー表（C-001〜C-013）', '', '設計モデルはゲート3（人の承認）より先に作られているため、現在のモデルは**暫定**。各行の「置換した範囲」以外は旧資料の記録として保持し、行全体を破棄も承認もしていない（機械検査 DR-12）。', '',
             '| ID | intentの該当文（引用と位置） | 置換した旧資料の範囲 | 置換しない範囲 | 現在の扱い |', '|---|---|---|---|---|']
    for i in [f'C-{n:03}' for n in range(1, 14)]:
        e = ents[i]; r = e['reconciliation']
        quotes = '<br>'.join(f'intent.md:{rq_line[q]}「{esc(rqtext(q))}」' for q in r['adopted_requirement_refs'])
        affected = ', '.join(f'{a}({ents[a]["adoption"]})' for a in r['affected_refs'])
        lines.append(f"| {i} {esc(e['name'])} | {quotes} | {esc(r['scope'])}<br>影響ID: {esc(affected)} | {esc(r.get('retained_scope', '（未記載）'))} | 状態 `{r['state']}`。影響IDの adoption は上記のとおり（`superseded` なし）。{esc(r.get('clarification', ''))} |")
    whole = [e['id'] for e in m['entities'] if e['adoption'] == 'superseded']
    lines += ['', f"行全体の破棄（adoption=superseded）: {refs(whole) if whole else 'なし'}（図の非常停止検知線とそのラベルのみ。C-017 の根拠付き）。承認済み（design_status=承認済み）: {sum(e['design_status'] == '承認済み' for e in m['entities'])} 件。", '']
    (GEN / 'gate3_review_C001_C013.md').write_text('\n'.join(lines) + '\n')

    # ---------------- e-stop impact ----------------
    pat = re.compile('|'.join(map(re.escape, ESTOP_TERMS)), re.I)
    rows = [json.loads(s) for s in (EXTRACT / 'excel_rows.jsonl').read_text().splitlines()]
    draws = [json.loads(s) for s in (EXTRACT / 'drawio_objects.jsonl').read_text().splitlines()]
    row_target = {(d['sheet'], d['row']): d['target_ref'] for d in m['migration']['row_dispositions']}
    dg_by_orig = {srcs[e['source_refs'][0]]['locator']['element_id']: e['id'] for e in m['entities'] if e['kind'].startswith('diagram_')}
    c017 = ents['C-017']['reconciliation']
    def handling(eid):
        e = ents.get(eid)
        if not e: return '（モデル対応なし）'
        if eid in c017['affected_refs']: return f"**不採用（C-017, RQ-I072）** adoption={e['adoption']}"
        if 'boundary' in e: return f"**未確認**（{e['boundary']['decision_ref']}: {esc(e['boundary']['note'])}）"
        if 'C-017' in e['related_refs']: return f"範囲外・保持（PC外のハードウェア事実、または観測不可の記載。機構ではない。C-017 retained_scope）adoption={e['adoption']}"
        return f'保持 adoption={e["adoption"]}'
    lines = [HEADER, '# 非常停止関連語の影響範囲一覧', '', f"検索語: {', '.join(ESTOP_TERMS)}（大文字小文字を区別しない）。対象: Excel 全シートの保存行、drawio 全要素。扱いはモデル（C-017・boundary・related_refs）から導出。", '',
             '## Excel', '', '| シート | 行 | ID | 一致セル | 原文 | モデル上の扱い |', '|---|---|---|---|---|---|']
    hits_x = 0
    for r in rows:
        hits = {k: v for k, v in r['values'].items() if isinstance(v, str) and pat.search(v)}
        if not hits: continue
        hits_x += 1; tid = row_target.get((r['sheet'], r['row']))
        for k, v in hits.items():
            lines.append(f"| {r['sheet']} | {r['row']} | {tid} | {k} | {esc(v)} | {handling(tid)} |")
    lines += ['', '## drawio', '', '| 要素ID | 種別 | 原文 | source → target | モデルID | モデル上の扱い |', '|---|---|---|---|---|---|']
    hits_d = 0
    for d in draws:
        text = json.dumps({k: d[k] for k in ('value_raw', 'source', 'target')}, ensure_ascii=False)
        if not pat.search(text) and d['id'] not in ('x5bDQh8FaZrcMh8EckeY-164', 'x5bDQh8FaZrcMh8EckeY-22', 'x5bDQh8FaZrcMh8EckeY-23', 'x5bDQh8FaZrcMh8EckeY-94'): continue
        hits_d += 1; mid = dg_by_orig[d['id']]
        lines.append(f"| {d['id']} | {d['kind']} | {esc(re.sub('<[^>]+>', '', d['value_raw'] or ''))} | {d.get('source')} → {d.get('target')} | {mid} | {handling(mid)} |")
    lines += ['', f'Excel 一致行 {hits_x} 件、drawio 該当要素 {hits_d} 件（線 x5bDQh8FaZrcMh8EckeY-164 とその端点・ラベルを含む）。', '',
              '## 不採用の範囲（C-017 scope 原文）', '', c017['scope'], '', '## 置換しない範囲（C-017 retained_scope 原文）', '', c017['retained_scope'], '',
              '## 関連する S・T・Q・ST', '', '- S-05（基本仕様!A6:D6）: 観測不可の記載。保持。', '- D-14（データ契約!A15:E15）: 観測不可の記載。保持。', '- ST: 非常停止を契機とする状態遷移行はない（状態遷移シート全20行に該当語なし）。', '- T: 非常停止に関する試験行はない（使用・開発検証シート全25行に該当語なし）。', '- Q: 非常停止に関する未決事項行はない。Q-09（Bluetooth切断時のP状態）は別問題として保持。', '']
    (GEN / 'impact_estop.md').write_text('\n'.join(lines) + '\n')

    # ---------------- lower design r2 ----------------
    nodes = [e for e in m['entities'] if e['kind'] == 'ros_node']
    ifs = [e for e in m['entities'] if e['kind'] == 'designed_interface']
    trans = [e for e in m['entities'] if e['kind'] == 'transition' and 'transition' in e]
    sos = [e for e in m['entities'] if e['kind'] == 'state_owner' and 'state_items' in e['state_owner']]
    prms = [e for e in m['entities'] if e['kind'] == 'parameter' and e.get('revision_ref')]
    modes = {e['id']: e for e in m['entities'] if e['kind'] == 'mode' and e['mode']['runtime']}
    def mname(i): return '（起動）' if i is None else modes[i]['mode']['current_name']
    lines = [HEADER, '# 下位設計案 r2（REV-002）', '', '**状態: 案。** 承認済み・ROSで動作確認済み・実車で検証済みのいずれでもない。版依存IFは実車PCの版照合（V-001）まで案。人の判断待ちは各行の問題IDを参照。', '',
             f"設計整合性検査: {design_check['overall']}（{json.dumps(design_check['result_counts'], ensure_ascii=False)}）。未判定の内訳は `reports/design_check.json`。", '',
             '## 1. 4つのソフトモードと遷移', '', '内部状態（goal送信中・取消待ち・復旧段階など）はモードではなく SO-01 の変数で持つ。', '',
             '| ID | 遷移 | イベント | 契機 | 種別 | 所有者 | guard | 動作 | 要求 | 未決 |', '|---|---|---|---|---|---|---|---|---|---|']
    for t in trans:
        tr = t['transition']
        lines.append(f"| {t['id']} | {mname(tr['from_mode_ref'])} → {mname(tr['to_mode_ref'])} | {tr['event_class']} | {esc(tr['trigger'])} | {tr['trigger_kind']} | {tr['owner_ref']} | {esc(tr['guard'])} | {esc('<br>'.join('・' + a for a in tr['actions']))} | {refs(t.get('requirement_refs', []))} | {refs(t['issue_refs'])} |")
    lines += ['', '## 2. 状態の所有者', '', '| ID | 所有Node | 状態 | 説明 | 永続化 | 復元範囲 |', '|---|---|---|---|---|---|']
    for s in sos:
        for it in s['state_owner']['state_items']:
            lines.append(f"| {s['id']} | {s['state_owner']['owner_ref']} | {it['name']} | {esc(it['description'])} | {it['persistence']} | {esc(it['restore_scope'])} |")
    lines += ['', '## 3. 責務と Node 分割の方針', '', f"旧 39 モジュールを {len(nodes)} の node／プロセス単位（外部ソフト・スクリプト含む）に整理。未確認要素（M-013, M-014 等）と後工程（M-021, M-022, M-024, M-029, M-030, M-033〜M-035）、ハードウェア（M-025〜M-028, M-031, M-032, M-036）、不採用（M-039: C-012）は node に置かない。", '',
              '| ID | node名 | 吸収した旧モジュール | 活性モード | lifecycle | プロセス群 | 責務 | 配置の理由 | 未決 |', '|---|---|---|---|---|---|---|---|---|']
    for n in nodes:
        r = n['ros_node']
        lines.append(f"| {n['id']} | `{r['node_name']}` | {refs(r['absorbs_module_refs'])} | {', '.join(mname(x) for x in r['active_in_mode_refs'])} | {r['lifecycle']} | {r['process_group']} | {esc('<br>'.join('・' + x for x in r['responsibilities']))} | {esc(r['placement_rationale'])} | {refs(n['issue_refs'])} |")
    placed = {x for n in nodes for x in n['ros_node']['absorbs_module_refs']}
    unplaced = [e['id'] for e in m['entities'] if e['kind'] == 'module' and e['id'] not in placed]
    lines += ['', f"node に吸収していない旧モジュール: {refs(unplaced)}", '',
              '## 4. 主要IF', '', '| ID | 名称 | transport | 型 | 標準 | 用途 | 所有者 | 発行/提供 | 購読/利用 | 単位 | frame | 時刻の意味 | QoS | 版依存 | 旧IF | 未決 |', '|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|']
    for e in ifs:
        d = e['designed_interface']; q = d['qos']
        lines.append(f"| {e['id']} | {esc(d['name'])} | {d['transport']} | {esc(d['message_type'])} | {'標準' if d['standard_type'] else '独自: ' + esc(d['custom_type_reason'] or '')} | {d['purpose']} | {d['owner_ref'] or '共有（各発行元）'} | {', '.join(d['publisher_refs'])} | {', '.join(d['consumer_refs'])} | {esc(d['unit'] or '-')} | {esc(d['frame'] or '-')} | {esc(d['time_semantics'])} | {q['reliability']}/{q['durability']}/{q['history_depth'] or '-'} | {d['version_dependency']['status']} | {refs(d['legacy_refs'])} | {refs(e['issue_refs'])} |")
    lines += ['', '## 5. パラメータ（値は intent.md:99 の転記または未確定。実測値ではない）', '', '| ID | 名称 | 所有者 | 値 | 状態 | 単位 | 備考 | 未決 |', '|---|---|---|---|---|---|---|---|']
    for p in prms:
        pp = p['parameter']
        lines.append(f"| {p['id']} | {esc(p['name'])} | {pp['owner_ref']} | {pp['value'] if pp['value'] is not None else '未確定'} | {pp['value_state']} | {pp['unit'] or '-'} | {esc(p['interpretation'])} | {refs(p['issue_refs'])} |")
    h1 = ents['H-001']['issue']
    lines += ['', '## 6. H-001 SpeedLimit 発行方式の比較（承認は人: DEC-011）', '', h1['question'], '', '| 案 | 評価 |', '|---|---|']
    for o in h1['options']: lines.append(f"| {esc(o['label'])} | {esc(o['effect'])} |")
    lines += ['', f"推奨: {h1['recommendation']}", '', f"根拠: {h1['recommendation_basis']}", '', f"影響ID: {refs(h1['affected_refs'])}", '',
              '## 7. 未確認の境界要素（設計に使っていない）', '', '| ID | 原文（抜粋） | 解釈 | 影響 | 人への質問 |', '|---|---|---|---|---|']
    for e in m['entities']:
        if 'boundary' not in e: continue
        s = srcs[e['source_refs'][0]]; raw = s['raw_fields']
        snippet = raw.get('value_raw') if s['kind'] == 'drawio_object' else ' / '.join(f'{k}:{v}' for k, v in list(raw.items())[1:4])
        lines.append(f"| {e['id']} | {esc(re.sub('<[^>]+>', '', str(snippet))[:120])} | {esc(e['boundary']['note'])} | {refs(e['issue_refs'])} | {e['boundary']['decision_ref']}（{decisions[e['boundary']['decision_ref']]['status']}） |")
    (GEN / 'lower_design_r2.md').write_text('\n'.join(lines) + '\n')

    # ---------------- human decisions (top 10 by affected count) ----------------
    humans = [e for e in m['entities'] if e['kind'] == 'issue' and e['issue']['category'] == 'human' and e['issue']['state'] in ('open', 'partially_superseded')]
    humans.sort(key=lambda e: (-len(e['issue']['affected_refs']), e['id']))
    stage = {'H-005': 'TF・Nav2設定・footprint を作る前（最初）', 'H-001': 'Nav2 BT/設定の実装前', 'H-002': '車体出力（motion_controller/bridge）の実装前', 'H-004': 'supervisor の採否と同時（車体出力実装前）', 'H-003': '障害物フィルタ設計前',
             'H-006': '復旧手順の実装前', 'H-007': 'PC再起動復帰の実装前', 'H-008': 'モード遷移の実装前', 'Q-05': '該当機能の実装前に設計値、試験で校正', 'Q-12': 'Nav2 設定（RemovePassedGoals radius 等）の前', 'Q-07': 'Nav2 planner/controller 構成の前', 'Q-10': '状態遷移の実装前', 'Q-04': '障害物処理と実車走行の評価前', 'Q-06': 'Nav2 設定・経路検証の実装前'}
    lines = [HEADER, '# 人の判断事項（影響IDの件数順、最大10件）', '', f"全 {len(humans)} 件のうち上位10件。順序の基準は issue.affected_refs の件数（同数は ID 順）。各件の選択肢・推奨・影響ID・決定段階を示す。推奨は未採用の判断材料であり、承認は人が行う。", '']
    for e in humans[:10]:
        q = e['issue']
        lines += [f"## {e['id']} {e['name']}", '', q['question'], '', '選択肢:'] + [f"- {o['label']}：{o['effect']}" for o in q['options']] + ['', f"推奨: {q['recommendation']}", f"根拠: {q.get('recommendation_basis', '')}", f"影響ID（{len(q['affected_refs'])}件）: {refs(q['affected_refs'])}", f"決定が必要な段階: {stage.get(e['id'], '次の下位設計段階')}", f"判断台帳: {', '.join(d for d in decisions if e['id'] in decisions[d]['resulting_refs']) or '（旧Q。台帳項目は未作成）'}", '']
    if len(humans) > 10: lines += ['## 11件目以降', ''] + [f"- {e['id']} {e['name']}（影響 {len(e['issue']['affected_refs'])} 件）" for e in humans[10:]] + ['']
    (GEN / 'human_decisions_r2.md').write_text('\n'.join(lines) + '\n')

    # ---------------- parameters by implementation stage ----------------
    STAGES = ['起動と記録', 'gouda_monitor', '地図作成と変換', 'waypoint', '車体出力', '自律走行の為の最小構成', 'blocked・一時停止・復帰', '安全機能']
    params = [e for e in m['entities'] if e['kind'] == 'parameter' and e.get('revision_ref')]
    legacy_params = [e for e in m['entities'] if e['kind'] == 'parameter' and not e.get('revision_ref')]
    lines = [HEADER, '# パラメータ一覧（実装段階の順）', '', 'DEC-017 の指示による一覧。「実車採用値」は value_state=approved かつ実測根拠があるものだけ。source_value は intent.md の記載値（実測ではない）。「ソフト設計用の仮値」は stub・シミュレーション試験で使う値で、実車には採用しない。一般論で値を補っていない（仮値の根拠は basis 欄）。', '',
             '| 段階 | ID | パラメータ | 用途 | 必要な実測 | 決定期限 | 実車採用値 | 値の状態 | ソフト設計用の仮値 | 仮値の根拠 | 未決 |', '|---|---|---|---|---|---|---|---|---|---|---|']
    order = {s_: i for i, s_ in enumerate(STAGES)}
    for p in sorted(params, key=lambda e: (order.get(e['parameter'].get('stage'), 99), e['id'])):
        pp = p['parameter']
        adopted = f"{pp['value']} {pp['unit'] or ''}" if pp['value_state'] == 'approved' else '未確定' if pp['value_state'] == 'unresolved' else f"（記載値 {pp['value']} {pp['unit'] or ''}。実測未）"
        lines.append(f"| {pp.get('stage') or '-'} | {p['id']} | {esc(p['name'])} | {esc(pp.get('purpose') or '-')} | {esc(pp.get('measurement') or '-')} | {esc(pp.get('decision_deadline') or '-')} | {esc(adopted)} | {pp['value_state']} | {pp.get('software_trial_value') if pp.get('software_trial_value') is not None else '-'} | {esc(pp.get('software_trial_basis') or '-')} | {refs(p['issue_refs'])} |")
    lines += ['', f"旧資料のパラメータ群（PAR-M-xxx、{len(legacy_params)} 件）は原文参照のまま未分解（G-PARAM）。個別キーへの分解は該当 node の実装段階で行う。", '']
    (GEN / 'parameters_by_stage.md').write_text('\n'.join(lines) + '\n')

    # ---------------- measurement plan ----------------
    meas = collections.defaultdict(list)
    for p in params:
        pp = p['parameter']
        if pp.get('measurement') and not str(pp['measurement']).startswith('不要'): meas[pp['measurement']].append(p)
    lines = [HEADER, '# 実測計画（DEC-032）', '', 'AI が測定計画と採用根拠を整理し、人が実測への協力と採用判断を行う。値は実測後に人が採用を判断するまで実車採用値にしない。測定なしで進められる設計は仮値（parameters_by_stage.md）で先に進める。', '',
             '| 実測 | 対象パラメータ | 用途 | 決定期限（最も早いもの） | 人に依頼すること | 採用根拠（人が判断する材料） |', '|---|---|---|---|---|---|']
    for mtxt, ps in sorted(meas.items(), key=lambda kv: min(order.get(x['parameter'].get('stage'), 99) for x in kv[1])):
        ids = ', '.join(x['id'] for x in ps); purposes = '<br>'.join(sorted({esc(x['parameter'].get('purpose') or '') for x in ps}))
        deadline = sorted((x['parameter'].get('decision_deadline') or '-' for x in ps))[0]
        lines.append(f"| {esc(mtxt)} | {ids} | {purposes} | {esc(deadline)} | 実車・実機での計測への協力（手順は実装段階で AI が作成し、記録は design/research/vehicle_pc/ 以下に保存） | 計測記録（日付・条件・生データ）と AI の解析結果。これを見て人が採用値を決める |")
    lines += ['', '測定なしで進められる部分: 仮値のある項目（parameters_by_stage.md の「ソフト設計用の仮値」列）は stub・シミュレーションでの設計・試験を先に進める。仮値を実車に流用しない。', '']
    (GEN / 'measurement_plan.md').write_text('\n'.join(lines) + '\n')

    # ---------------- review package r3 ----------------
    tests = [e for e in m['entities'] if e['kind'] == 'test' and e.get('revision_ref')]
    rev = m['revisions'][-1]
    approved_ids = [e['id'] for e in m['entities'] if e['design_status'] == '承認済み']
    gate3 = decisions.get('DEC-053')
    gate3_line = (f"状態: ゲート3は条件付き・範囲限定で承認（DEC-053、{gate3['answered_on']}。暫定ベースライン＝FILE-GATE3-MODEL）。122 件の design_status は案のまま（個別最終承認ではない）。" if gate3 and gate3['status'] == 'answered'
                  else '状態: 案。ゲート3（人の承認）が済むまで工程5は暫定扱い（DEC-019）。')
    lines = [HEADER, f"# レビュー資料 r3（{rev['id']}。工程5-1 の前のレビュー）", '', f"{gate3_line} 承認済み（人の決定値）は {refs(approved_ids)}。設計検査合格／ソフト試験合格／実車検証済みは別の状態で、ROS 動作確認・実車検証は未実施。", '',
             f"モデル: {len(m['entities'])} 要素、revisions {len(m['revisions'])}、decisions {len(m['decisions'])}（pending {sum(d['status'] == 'pending' for d in m['decisions'])}）。検査: `reports/migration_validation.json`（忠実性）、`reports/design_check.json`（設計整合性 {design_check['overall']}）。", '',
             '## 1. 遷移表', '', '| ID | 遷移 | イベント | 契機 | 種別 | guard | 動作 | 未決 |', '|---|---|---|---|---|---|---|---|']
    for t in trans:
        tr = t['transition']
        lines.append(f"| {t['id']} | {mname(tr['from_mode_ref'])} → {mname(tr['to_mode_ref'])} | {tr['event_class']} | {esc(tr['trigger'])} | {tr['trigger_kind']} | {esc(tr['guard'])} | {esc('<br>'.join('・' + a for a in tr['actions']))} | {refs(t['issue_refs'])} |")
    lines += ['', '## 2. IF 一覧（変更のあったもの・新規を含む全件）', '', '| ID | 名称 | transport | 型 | 所有者 | 発行 | 購読 | QoS | 時刻の意味 | 版 | 未決 |', '|---|---|---|---|---|---|---|---|---|---|---|']
    for e in ifs:
        d = e['designed_interface']; q = d['qos']
        lines.append(f"| {e['id']} | {esc(d['name'])} | {d['transport']} | {esc(d['message_type'])} | {d['owner_ref'] or '共有'} | {', '.join(d['publisher_refs'])} | {', '.join(d['consumer_refs'])} | {q['reliability']}/{q['durability']}/{q['history_depth'] or '-'} | {esc(d['time_semantics'])} | {d['version_dependency']['status']} | {refs(e['issue_refs'])} |")
    fault_events = {'nav_failure': 'Nav2 BT の失敗', 'fault_recovery': 'node 異常・推定不能・通信途絶', 'recovery_failed': '自動復帰不能・試行上限', 'pc_restart': 'PC 再起動'}
    tests_for = collections.defaultdict(list)
    for t_ in m['entities']:
        if t_['kind'] == 'test' and t_.get('revision_ref'):
            for r_ in t_['related_refs']: tests_for[r_].append(t_['id'])
    boundary_ids = {e['id'] for e in m['entities'] if 'boundary' in e}
    lines += ['', '## 3. 故障時の対応（設計した遷移から導出。故障モード表は generated/failure_modes.md）', '', '| 故障・事象 | 検出 | 対応（遷移） | 復帰先 | 試験 | 記録 | 未確認要素への依存 | 検出できない故障 |', '|---|---|---|---|---|---|---|---|']
    for t in trans:
        tr = t['transition']
        if tr['event_class'] not in fault_events: continue
        dep = sorted({b for b in boundary_ids if b in json.dumps(tr, ensure_ascii=False)} | ({tr['owner_ref']} & boundary_ids))
        lines.append(f"| {fault_events[tr['event_class']]}（{t['id']}） | {esc(tr['trigger'])} | {esc('<br>'.join('・' + a for a in tr['actions']))} | {mname(tr['to_mode_ref'])} | {refs(tests_for.get(t['id'], [])) or '（なし）'} | 停止原因区分・各段階の成否（RQ-I029・RQ-I013） | {refs(dep) if dep else 'なし（DR-07）'} | 非常停止押下・P介入・ESP32/DAC故障・電池・PC停止中の移動（proposals/undetectable_faults_r2.md） |")
    lines += ['', 'cmd_vel 途絶（RQ-I063）: motion_controller が PRM-08 で中立。motion_hold（IFD-40）の途絶も中立。ESP32 は PC 指令途絶で中立（RQ-I068、既存 firmware 250 ms。H-009）。', '',
              '## 4. 試験の期待結果（未実行）', '', '| ID | 試験 | 段階 | 手順 | 観察 | 期待結果 | 未決 |', '|---|---|---|---|---|---|---|']
    for t in tests:
        tp = t['test']
        lines.append(f"| {t['id']} | {esc(t['name'])} | {esc(tp.get('stage', '-'))} | {esc(tp.get('procedure', '-'))} | {esc(tp.get('observe', '-'))} | {esc(tp.get('expected', '-'))} | {refs(t['issue_refs'])} |")
    prm_all = [e for e in m['entities'] if e['kind'] == 'parameter' and e.get('revision_ref')]
    lines += ['', '## 4b. 宣言する部分と実行する部分の区別（RQ-I076）', '', '宣言（モデル→生成）: 下表の設定値。生成物は `generated/params/`（`tools/generate_params.py`）。実行（コードの状態遷移）: TR-01〜TR-16 の遷移と guard、SO-xx の状態保持。設定値はコードに埋め込まず、生成した parameter ファイル・firmware 設定・BT XML 置換値から読む。', '',
              '| ID | 設定キー | 型 | 単位 | 宣言先 | 設定先 | 適用時期 | 確定状態 |', '|---|---|---|---|---|---|---|---|']
    for p in sorted(prm_all, key=lambda e: e['id']):
        pp = p['parameter']
        lines.append(f"| {p['id']} | {esc(pp.get('param_key') or '-')} | {esc(pp.get('value_type') or '-')} | {esc(pp['unit'] or '-')} | {pp.get('declaration') or '-'} | {esc(pp.get('target') or '-')} | {pp.get('apply_timing') or '-'} | {pp['value_state']} |")
    lines += ['', '## 5. この版で反映した人の回答', '', '| 判断台帳 | 回答（原文） | 反映先 |', '|---|---|---|']
    for d in m['decisions']:
        if d['status'] == 'answered' and d.get('answered_on') == rev['date']: lines.append(f"| {d['id']} | {esc(d['answer_verbatim'])} | {refs(d['resulting_refs'])} |")
    lines += ['', '## 6. 残る人の判断', ''] + [f"- {e['id']} {e['name']}（判断台帳 {', '.join(x for x in decisions if e['id'] in decisions[x]['resulting_refs'] + decisions[x]['affected_refs']) or 'なし'}）" for e in m['entities'] if e['kind'] == 'issue' and e['issue']['category'] == 'human' and e['issue']['state'] in ('open', 'partially_superseded')] + ['']
    (GEN / 'review_r3.md').write_text('\n'.join(lines) + '\n')

    # ---------------- pending classification & gate3 package ----------------
    disp_label = {'resolved_by_existing': '既存の決定・回答済み事項で解消済み（閉じる）', 'gate3_bundle': 'ゲート3で一括承認する下位設計案', 'open_human': '本当に未決の人の判断', 'technical_pending': '技術調査・実測待ち（人の承認待ちから外す）', 'fact_check_pending': '実機照合待ち（人の承認待ちから外す）', 'answered': '回答済み'}
    lines = [HEADER, '# 判断台帳の分類（DEC-051）', '', '| 分類 | 判断台帳 | 対象 | 根拠・内容 |', '|---|---|---|---|']
    for key in ['resolved_by_existing', 'gate3_bundle', 'open_human', 'technical_pending', 'fact_check_pending']:
        for d in m['decisions']:
            if d.get('disposition') == key:
                lines.append(f"| {disp_label[key]} | {d['id']}（{d['status']}） | {refs(d['affected_refs'] + d['resulting_refs'])} | {esc(d['question'][:120])}<br>{esc(d['note'][:300])} |")
    undisp = [d['id'] for d in m['decisions'] if not d.get('disposition')]
    lines += ['', f"disposition 未設定（回答済み・記録のみ）: {', '.join(undisp)}", '', '## H-001 の台帳上の経緯', '', esc(ents['H-001']['issue']['next_action']), '']
    (GEN / 'pending_classification.md').write_text('\n'.join(lines) + '\n')

    approved = [e for e in m['entities'] if e['design_status'] == '承認済み']
    proposals = [e for e in m['entities'] if e['adoption'] == 'designed_proposal']
    answered = [d for d in m['decisions'] if d['status'] == 'answered']
    open_h = [e for e in m['entities'] if e['kind'] == 'issue' and e['issue']['category'] == 'human' and e['issue']['state'] in ('open', 'partially_superseded')]
    gate3 = decisions.get('DEC-053'); gate3_file = next((f for f in m['files'] if f['id'] == 'FILE-GATE3-MODEL'), None)
    if gate3 and gate3['status'] == 'answered':
        status_line = (f"状態: 条件付き・範囲限定で承認（DEC-053、{gate3['answered_on']}）。承認対象モデルは {gate3_file['path'] if gate3_file else '（未登録）'}（SHA-256 `{gate3_file['sha256'] if gate3_file else '-'}`、Git は未コミット）。"
                       f"下位設計案 {len(proposals)} 件は暫定ベースライン（design_status は案のまま。個別最終承認・未確定値の確定・未実施試験の合格・実車投入は含まない）。"
                       f"CLAUDE.md は修復済み（DEC-052）。工程と完了条件は docs/implementation_stages.md（DEC-056）。")
    else:
        status_line = '状態: 承認待ち。承認まで工程5は暫定（DEC-019）。CLAUDE.md の修復（DEC-052）が済むまで CLAUDE.md の指示に依存する新規作業は止める。'
    lines = [HEADER, '# ゲート3 承認資料', '', status_line, '',
             '## 1. 承認対象', '', f"### 1.1 下位設計案（adoption=designed_proposal、{len(proposals)} 件）", '']
    by_kind = collections.defaultdict(list)
    for e in proposals: by_kind[e['kind']].append(e['id'])
    for k in sorted(by_kind): lines.append(f"- {k}（{len(by_kind[k])}）: {refs(by_kind[k])}")
    gaps = []
    for prefix in ['IFD', 'ND', 'SO', 'TS', 'TR', 'PRM']:
        nums = sorted(int(e['id'].split('-')[1]) for e in m['entities'] if re.fullmatch(prefix + r'-\d+', e['id']))
        gaps += [f'{prefix}-{n:02}' for n in range(1, nums[-1] + 1) if n not in nums]
    removed = sorted({x for r in m['revisions'] for x in r['removed_entity_ids']})
    lines += ['', f"欠番: {', '.join(f'`{g}`' for g in gaps) if gaps else 'なし'}（割り当てなかった番号。削除した要素ではない: 全 revision の removed_entity_ids は {removed or '空'}。id_policy により再採番しない）"]
    lines += ['', f"### 1.2 人の決定（answered、{len(answered)} 件）を根拠にした要素", '', '| 判断台帳 | 回答（原文、先頭 100 字） | 反映先 |', '|---|---|---|']
    for d in answered: lines.append(f"| {d['id']} | {esc(d['answer_verbatim'][:100])} | {refs(d['resulting_refs'][:8]) if d['resulting_refs'] else 'モデル外: ' + esc(d['note'][:160])} |")
    lines += ['', f"### 1.3 承認済み（{len(approved)} 件、人の決定値）: {refs([e['id'] for e in approved])}", '',
              '## 2. 承認によって着手する作業（工程と完了条件は docs/implementation_stages.md）', '', '- 下位設計の継続: 独自型 4 件の .msg/.srv/.action 定義、速度マスク生成器・復帰手順・適用状態記録の詳細、新 firmware（G-FIRMWARE）の設計。',
              '- 実装（工程5-1 以降、intent.md:64 の順、機能単位。全 Node の一括実装はしない）: 起動（gouda.sh）と記録 → gouda_monitor → 地図作成と変換 → waypoint → 車体出力（gouda_motion_controller・vehicle_bridge・新 firmware。手動優先・入力途絶時の中立化・一時停止中の中立出力を完了条件に含める）→ 自律走行の最小構成 → blocked・一時停止・復帰 → 安全機能（対象要求 ID は同文書 §8。非常停止検知・PC 側非常停止は再導入しない: RQ-I072）。',
              '- 実車試験への移行は別の判断。設計検査・ソフト試験（TS-01〜16）・実測計画の結果を材料に人が判断する（実車投入可能は人の判断、CLAUDE.md 1.4）。', '',
              '## 3. 未確定事項と、それが止める作業', '', '| 未確定 | 止まる作業 | 進められる作業 |', '|---|---|---|']
    blockers = [('Q-05 実車値（timeout・周期・しきい値）', '実車での値の確定、TS-13・TS-07 の合格判定', '値を parameter で宣言した設計と stub 試験'),
                ('Q-06 車体・経路の幾何（footprint、速度刻み PRM-20）', 'Nav2 設定の値、速度マスクの実値', 'mask 生成器（幅を引数）・Nav2 設定の構造。帯幅 PRM-19 は実機調整（G-TUNING、DEC-055）'),
                ('Q-04 XT-32 の取付・可視範囲', '障害物フィルタの値、実車評価', 'フィルタの IF と処理の構造'),
                ('Q-02 自己位置推定の方式（AI 選定）', '推定器の実装', 'TF・Odometry・pose の IF 固定'),
                ('GLIM の版固定（dpkg 出力待ち）', 'IFD-35 の確定', '地図作成の IF・記録'),
                ('DEC-050 実機照合（配線・firmware・操作結果）', '車体出力の実車確認', '新 firmware の設計・ソフト試験'),
                ('RQ-I010 の境界文の削除（intent.md の人の編集待ち、DEC-055）', 'AR-006 の記録', '設計側は依存を外した（C-003 clarification、TS-14・TS-16）')]
    for a, b, c in blockers: lines.append(f'| {a} | {b} | {c} |')
    gate3b = decisions.get('DEC-058')
    if gate3b and gate3b['status'] == 'answered':
        lines += ['', '## 3b. ゲート3 第2回承認（DEC-058）の承認範囲と未解消の条件', '', '承認は「確認が完了した」意味ではない。各条件は該当する工程の前に解消し、人が確認する。', '', '回答（原文）:', '', '```', gate3b['answer_verbatim'].rstrip(), '```', '', '条件の状態（AI の対応と人の確認待ち）:', '']
        lines += ['- ' + ln for ln in gate3b['note'].strip().splitlines() if ln.strip()]
        lines += ['', f"衝突の登録: `C-023`（状態 {ents['C-023']['reconciliation']['state']}）、人の判断 `H-013`（{ents['H-013']['issue']['state']}、台帳 DEC-059 {decisions['DEC-059']['status']}）。基本契約の試験: " + refs(['TS-17', 'TS-18', 'TS-19', 'TS-20', 'TS-21']) + "（工程は docs/implementation_stages.md §1・§5）。"]
    lines += ['', '## 4. 上位要求からの変更・例外', '', '- 上位要求（intent.md）を AI が変更した箇所はない。intent.md の変更はすべて人の編集（AR-002〜006）。',
              '- RQ-I071（第2版の座標系の文）は人の編集で RQ-I074 に置換（C-021、AR-003）。RQ-I010（境界文）は人の編集で RQ-I078 に置換（C-022、AR-006、DEC-055）。DEC-007 により base_link は REP-103、LiDAR・IMU の座標方向は /config で指定して変換。',
              '- 基本契約の読み替え: なし。手動優先・一時停止操作・ESP32 の中立化は維持（DR-08 で機械確認）。DEC-042 で手動経路は「Bluetooth ゲームパッド→ESP32→DAC」で確定。',
              '- 例外・制約: Speed Filter は mask 未読込・マスク外で何も発行しない（Nav2 の挙動）→ 適用状態を記録・表示（DEC-047）。復帰は cleanup→configure→activate の 1 手順に限定（DEC-046）。',
              '- 旧資料の採用しない部分: 非常停止検知（C-017）、collision_stop_request（C-020）、Safety_gate／supervisor の permission（DEC-004）、旧 5 m（DEC-016）、指定線方式（Q-07 後工程）。いずれも行全体は破棄せず履歴保持。', '',
              '## 5. C-001〜C-013: 置換範囲が intent 該当文の範囲に収まっているか', '', '「置換した範囲」は REV-002（初回移行）時点の記述。「現在の扱い」列に、当時「未設計」とした事項が現在どう設計されたかを示す（DEC-054）。', '', '| ID | intent の該当文 | 置換した範囲（REV-002 時点） | 確認 | 現在の扱い |', '|---|---|---|---|---|']
    for i in [f'C-{n:03}' for n in range(1, 14)]:
        e = ents[i]; r = e['reconciliation']
        quotes = '<br>'.join(f"{q}: {esc(rqtext(q)[:80])}…" for q in r['adopted_requirement_refs'])
        lines.append(f"| {i} {esc(e['name'])} | {quotes} | {esc(r['scope'])} | {esc(r.get('scope_within_intent', '未確認'))} | {esc(r.get('clarification') or ('「未設計」の記述なし' if '未設計' not in r['scope'] else '未記載'))} |")
    lines += ['', '置換していない範囲（retained_scope）は generated/gate3_review_C001_C013.md。行全体の破棄（superseded）は図の 4 要素と RQ-I071 のみで、いずれも根拠付き（DR-12）。', '',
              '## 6. 残る人の判断（open）', ''] + [f"- {e['id']} {e['name']}" for e in open_h] + ['', '判断台帳の分類は generated/pending_classification.md。', '']
    (GEN / 'gate3_package.md').write_text('\n'.join(lines) + '\n')

    # ---------------- stop / resume conditions (DEC-056) ----------------
    STOP_EVENTS = ['start', 'pause', 'end', 'nav_failure', 'goal_reached', 'recovery_failed', 'pc_restart', 'fault_recovery', 'resume']
    def pick(texts, pats):
        return [t for t in texts if any(re.search(p_, t) for p_ in pats)]
    lines = [HEADER, '# 停止・復帰の成立条件（モデルの遷移から導出。DEC-056）', '',
             '各遷移の guard・actions から、(1) 旧 goal の終了または破棄、(2) 人の一時停止・終了操作の保持、(3) 指令中立化の担当、を機械的に抜き出した。抜き出せない項目は「欠落」と表示する（設計の欠落か、文言の欠落かは人が確認）。'
             ' 人の操作の保持は SO-01 の previous_mode_record（persisted）で行い、PC 再起動後の走行再開を禁じる（RQ-I025、TR-02 の guard）。中立化の最終段は ESP32 の指令途絶中立（RQ-I068、PRM-13）。', '',
             '| 遷移 | イベント | (1) 旧 goal の終了／破棄 | (2) 人の操作の保持 | (3) 中立化の担当 |', '|---|---|---|---|---|']
    missing = []
    for t in trans:
        tr = t['transition']
        if tr['event_class'] not in STOP_EVENTS: continue
        texts = list(tr['actions']) + [tr['guard']]
        g = pick(texts, [r'goal.*(終了|破棄|取消|残っていない|送信)'])
        h = pick(texts, [r'直前モード記録|RQ-I025|人の(一時停止|終了|操作)'])
        n = pick(texts, [r'motion_hold|中立'])
        for label, got in (('旧goal', g), ('人の操作', h), ('中立化', n)):
            if not got: missing.append(f'{t["id"]}: {label}')
        cell = lambda xs: esc('<br>'.join('・' + x for x in xs)) if xs else '**欠落**'
        lines.append(f"| {t['id']} {esc(t['name'])} | {tr['event_class']} | {cell(g)} | {cell(h)} | {cell(n)} |")
    lines += ['', f"欠落: {', '.join(missing) if missing else 'なし'}", '',
              '試験との対応: TS-04（一時停止時の中立）、TS-07（motion_hold による中立）、TS-13（cmd_vel 途絶）、TS-08（PC 再起動後の再開は人の初期位置要求後）、TS-06（復帰後の上限の再適用。適用を確認できない経路では自動再走行しない）、TS-05（Action 結果による旧 goal の終了）。', '']
    (GEN / 'stop_resume_conditions.md').write_text('\n'.join(lines) + '\n')

    # ---------------- failure modes (DEC-056): transitions + input-loss parameters, with transition/test refs ----------------
    lines = [HEADER, '# 故障モード表（モデルから導出。DEC-056）', '',
             '各行は設計した遷移（TR）と試験（TS）を参照する。対策の根拠に未確認（boundary）の要素は使わない（DR-07 で機械確認）。非常停止検知・PC 側非常停止は検出手段にも対策にも含めない（RQ-I072、DR-06）。検出できない故障は proposals/undetectable_faults_r2.md（提案）。', '',
             '| 故障・事象 | 検出（誰が・何で） | 対応 | 遷移 | 試験 | 時間値 | 未確認要素への依存 |', '|---|---|---|---|---|---|---|']
    for t in trans:
        tr = t['transition']
        if tr['event_class'] not in fault_events: continue
        dep = sorted({b for b in boundary_ids if b in json.dumps(tr, ensure_ascii=False)})
        lines.append(f"| {fault_events[tr['event_class']]} | {esc(tr['trigger'])}（{tr['owner_ref']}） | {esc('<br>'.join('・' + a for a in tr['actions']))} | {t['id']} → {mname(tr['to_mode_ref'])} | {refs(tests_for.get(t['id'], [])) or '（なし）'} | PRM-10（試行上限、未確定） | {refs(dep) if dep else 'なし'} |")
    prm = {e['id']: e['parameter'] for e in m['entities'] if e['kind'] == 'parameter' and e.get('revision_ref')}
    def pv(i): p_ = prm[i]; return f"{i}={p_['value']} {p_['unit'] or ''}（{p_['value_state']}）"
    loss_rows = [('cmd_vel の途絶（Nav2→motion_controller）', 'ND-11 が最終受信時刻で判定（SO-08）', '正規化操作値を中立にして発行を続ける（RQ-I063）', 'TR-06・TR-13 と独立（常時）', ['TS-07', 'TS-13'], pv('PRM-08')),
                 ('motion_hold の途絶（mode_manager→motion_controller）', 'ND-11 が周期発行の期限で判定', 'hold 扱い＝中立（DEC-004）', '—', ['TS-07'], pv('PRM-16')),
                 ('joystick_command の期限切れ（motion_controller→bridge）', 'ND-12 が header.stamp で判定', '中立の COMMAND を送り続ける。古い指令を再送しない', '—', ['TS-13'], pv('PRM-09')),
                 ('有効な PC 指令フレームの途絶（bridge→ESP32）', 'ND-17 が最後の有効指令の受信時刻で判定（SO-11）', 'DAC を中立にする。リレー解除はしない（RQ-I068・RQ-I077）', '—', [], pv('PRM-13')),
                 ('Bluetooth ゲームパッド報告の途絶', 'ND-17 が報告の受信時刻で判定', '手動入力を無効にし中立（RQ-I024。既存動作を維持、DEC-048）', '—', [], pv('PRM-21'))]
    for a, b, c, d_, ts, v in loss_rows: lines.append(f"| {a} | {b} | {c} | {d_} | {refs(ts) or '（新 firmware 試験、車体出力工程で追加）'} | {v} | なし |")
    lines += ['', '旧資料の異常時動作（FM-M-xxx、Excel 原文）は参照のまま。完成版の故障モード表ではなく、設計した遷移・パラメータから機械的に導出した一覧である。', '']
    (GEN / 'failure_modes.md').write_text('\n'.join(lines) + '\n')

    # ---------------- YAML views at requested paths ----------------
    y = YAML(); y.allow_unicode = True; y.width = 110; y.indent(mapping=2, sequence=4, offset=2)
    def dump(path, obj, note):
        with path.open('w') as f:
            f.write('# GENERATED by design/tools/render_views.py from design/model.yaml — do not edit.\n# ' + note + '\n'); y.dump(obj, f)
    conflicts = [{'id': e['id'], 'name': e['name'], 'state': e['reconciliation']['state'], 'adopted_requirement_refs': e['reconciliation']['adopted_requirement_refs'],
                  'intent_lines': [rq_line[q] for q in e['reconciliation']['adopted_requirement_refs']], 'affected_refs': e['reconciliation']['affected_refs'],
                  'scope': e['reconciliation']['scope'], 'retained_scope': e['reconciliation'].get('retained_scope'), 'clarification': e['reconciliation'].get('clarification'),
                  'issue_refs': e['reconciliation']['issue_refs'], 'sources': [pos(s) for s in e['source_refs']]} for e in m['entities'] if e['kind'] == 'reconciliation']
    dump(DESIGN / 'conflicts.yaml', {'generated_from': 'design/model.yaml (kind=reconciliation)', 'count': len(conflicts), 'conflicts': conflicts}, '衝突・変更対応の一覧ビュー。正本は model.yaml の reconciliation。')
    open_items = []
    for e in m['entities']:
        if e['kind'] != 'issue' or e['issue']['state'] not in ('open', 'partially_superseded'): continue
        q = e['issue']
        open_items.append({'id': e['id'], 'name': e['name'], 'category': q['category'], 'state': q['state'], 'question': q['question'], 'next_action': q['next_action'],
                           'intent_lines': sorted({rq_line[r] for r in e.get('requirement_refs', []) + [a for a in q['affected_refs'] if a.startswith('RQ-')] if r in rq_line}, key=str),
                           'affected_refs': q['affected_refs'], 'options': q.get('options'), 'recommendation': q.get('recommendation'),
                           'decision_refs': [d for d in decisions if e['id'] in decisions[d]['resulting_refs']]})
    pending = [{'id': d['id'], 'kind': d['kind'], 'status': d['status'], 'question': d['question'], 'resulting_refs': d['resulting_refs']} for d in decisions.values() if d['status'] == 'pending']
    dump(DESIGN / 'intent_open_items.yaml', {'generated_from': 'design/model.yaml (kind=issue, state open/partially_superseded; decisions pending)', 'issue_count': len(open_items), 'pending_decision_count': len(pending), 'issues': open_items, 'pending_decisions': pending}, '未決事項の一覧ビュー。正本は model.yaml の issue と decisions。')
    index = []
    for line in sorted(linemap):
        rq = linemap[line]
        referencing = sorted({e['id'] for e in m['entities'] if rq in e.get('requirement_refs', []) or (e['kind'] == 'reconciliation' and rq in e['reconciliation']['adopted_requirement_refs']) or (e['kind'] == 'issue' and rq in e['issue']['affected_refs'])})
        index.append({'line': line, 'requirement_id': rq, 'text': rqtext(rq), 'source_id': ents[rq]['source_refs'][0], 'authority_file': srcs[ents[rq]['source_refs'][0]]['file_ref'], 'referenced_by': referencing, 'issue_refs': ents[rq]['issue_refs']})
    dump(DESIGN / 'intent_index.yaml', {'generated_from': 'design/model.yaml (kind=requirement) + intent.md', 'authority': {f['id']: {'sha256': f['sha256'], 'role': f['role']} for f in m['files'] if f['role'].startswith('authority')}, 'line_count': len(index), 'lines': index}, 'intent.md の行→要求ID→参照要素の索引。正本は model.yaml。')

    # ---------------- model diff vs baseline ----------------
    base = load_yaml(BASELINE / 'model.yaml'); bents = {e['id']: e for e in base['entities']}
    added = [e for e in m['entities'] if e['id'] not in bents]; modified = []
    for bid, be in bents.items():
        cur = ents[bid]
        if canonical(be) != canonical(cur):
            changed = sorted(set(k for k in set(be) | set(cur) if canonical(be.get(k)) != canonical(cur.get(k))))
            modified.append((bid, changed))
    rev = m['revisions'][-1]
    lines = [HEADER, f"# モデル差分 {rev['id']}（baseline migration_v1 → 現在）", '', f"baseline: `design/baselines/migration_v1/model.yaml`（{json.loads((BASELINE / 'snapshot.json').read_text())['design/model.yaml'][:16]}…）。削除 0 件（検査で禁止）。", '',
             f"追加 {len(added)} 要素: " + json.dumps(dict(collections.Counter(e['kind'] for e in added)), ensure_ascii=False), '', '| 追加ID | kind | 名称 |', '|---|---|---|'] + [f"| {e['id']} | {e['kind']} | {esc(e['name'])} |" for e in added]
    lines += ['', f"変更 {len(modified)} 要素（変更されたフィールド）:", '', '| ID | 変更フィールド |', '|---|---|'] + [f"| {i} | {', '.join(c)} |" for i, c in modified]
    lines += ['', f"追加 source: {', '.join(rev['added_source_ids'])}；追加 file: {', '.join(rev['added_file_ids'])}；schema_version {base['schema_version']} → {m['schema_version']}；metadata.authority_ref {base['metadata']['authority_ref']} → {m['metadata']['authority_ref']}", '',
              '新設セクション: `authority_revisions`（intent 版）, `revisions`（変更記録）, `decisions`（判断台帳）。', '']
    (DESIGN / 'reports' / f"model_diff_{rev['id'].lower().replace('rev-00', 'r')}.md").write_text('\n'.join(lines) + '\n')
    print('rendered', [str(p.relative_to(ROOT)) for p in [GEN / 'gate3_review_C001_C013.md', GEN / 'impact_estop.md', GEN / 'lower_design_r2.md', GEN / 'human_decisions_r2.md', GEN / 'gate3_package.md', GEN / 'stop_resume_conditions.md', GEN / 'failure_modes.md', DESIGN / 'conflicts.yaml', DESIGN / 'intent_open_items.yaml', DESIGN / 'intent_index.yaml']])


if __name__ == '__main__': main()
