#!/usr/bin/env python3
"""Generate include/gouda_v4/build_config.hpp from design/generated/params/firmware_config.yaml (RQ-I076, DR-15).

Runs as a PlatformIO pre-build extra script (reads GOUDA_TRIAL from the build flags) or standalone:
  python3 tools/gen_build_config.py [--trial] [--out path]
Only the generated parameter files are read; nothing is defaulted. When any of the 9 configuration items is missing the
header says has_config=false and the firmware starts unconfigured (DAC not written, config_valid=0) until the PC registers
a full configuration with SET_CONFIG. The trial file (software trial values) is read only with --trial / GOUDA_TRIAL=1:
desk and stub tests only, never a vehicle build.
"""
import os
import re
import sys
from pathlib import Path

try:                      # PlatformIO extra-script context: no __file__, the project dir comes from the build environment
    Import('env')  # noqa: F821
    HERE = Path(env.subst('$PROJECT_DIR')).resolve() / 'tools'  # noqa: F821
    PIO_ENV = env  # noqa: F821
except NameError:
    HERE = Path(__file__).resolve().parent
    PIO_ENV = None
REPO = HERE.parents[2]
PARAMS = REPO / 'design' / 'generated' / 'params'
KEYS = ['dac_neutral_mv', 'dac_min_mv', 'dac_max_mv', 'dac_full_scale_mv', 'pc_command_watchdog_ms', 'bt_report_timeout_ms',
        'manual_deadzone_q10000', 'manual_release_neutral_ms', 'status_period_ms']
SECONDS = {'pc_command_watchdog_s': 'pc_command_watchdog_ms', 'bt_report_timeout_s': 'bt_report_timeout_ms'}


def read_flat(path: Path) -> dict:
    """`key: value  # comment` lines of the generated flat firmware files (no PyYAML dependency inside PlatformIO's venv)."""
    out = {}
    if not path.is_file():
        return out
    for line in path.read_text(encoding='utf-8').splitlines():
        m = re.match(r'^([A-Za-z_]\w*):\s*([-+]?\d+(?:\.\d+)?)\s*(#.*)?$', line)
        if m:
            out[m.group(1)] = float(m.group(2))
    return out


def wire_config(trial: bool) -> tuple:
    merged = read_flat(PARAMS / 'firmware_config.yaml'); sources = ['firmware_config.yaml']
    if trial:
        merged.update(read_flat(PARAMS / 'firmware_config.trial.yaml')); sources.append('firmware_config.trial.yaml')
    cfg = {}
    for k, v in merged.items():
        if k in SECONDS: cfg[SECONDS[k]] = int(round(v * 1000))
        elif k in KEYS: cfg[k] = int(round(v))
    return cfg, sources


def render(trial: bool) -> str:
    cfg, sources = wire_config(trial)
    missing = [k for k in KEYS if k not in cfg]
    has = not missing
    items = [cfg.get(k, 0) for k in KEYS] + [0]
    lines = ['// GENERATED by firmware/gouda_esp32_v4/tools/gen_build_config.py from design/generated/params/' + ' + '.join(sources),
             '// Do not edit. Change the design model (design/revisions) and regenerate. No value here is typed by hand.',
             '#pragma once', '#include <cstdint>', 'namespace gouda_v4 { namespace build_config {',
             f'constexpr bool trial = {"true" if trial else "false"};   // true = software trial values included: DESK/STUB TESTS ONLY, never the vehicle',
             f'constexpr bool has_config = {"true" if has else "false"};' + ('' if has else f'   // missing: {", ".join(missing)}'),
             'constexpr uint16_t items[10] = {' + ', '.join(str(i) for i in items) + '};   // order: docs/esp32_protocol_v4.md §5',
             f'constexpr const char* source = "{" + ".join(sources)}";',
             '} }', '']
    return '\n'.join(lines)


def write(trial: bool, out: Path) -> None:
    text = render(trial)
    out.parent.mkdir(parents=True, exist_ok=True)
    if not out.is_file() or out.read_text(encoding='utf-8') != text:
        out.write_text(text, encoding='utf-8')
    print(f'gen_build_config: {out} (trial={trial})')


def main(argv):
    trial = '--trial' in argv
    out = HERE.parent / 'include' / 'gouda_v4' / 'build_config.hpp'
    if '--out' in argv: out = Path(argv[argv.index('--out') + 1])
    write(trial, out)


if PIO_ENV is not None:
    flags = ' '.join(str(f) for f in PIO_ENV.get('BUILD_FLAGS', []))
    write('-DGOUDA_TRIAL=1' in flags, HERE.parent / 'include' / 'gouda_v4' / 'build_config.hpp')
elif __name__ == '__main__':
    main(sys.argv[1:])
