[env:encoder_mock]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = emc270_core=symlink://../common
build_flags =
  -std=gnu++17
  -Wall
  -Wextra
build_unflags = -std=gnu++11
