<?xml version="1.0"?>
<package format="3"><name>gouda_gui</name><version>0.1.0</version>
<description>Gouda mission control</description>
<maintainer email="ryoya-1@g.ecc.u-tokyo.ac.jp">Gouda Development Team</maintainer>
<license>Apache-2.0</license><buildtool_depend>ament_python</buildtool_depend>
<exec_depend>rclpy</exec_depend><exec_depend>nav_msgs</exec_depend>
<exec_depend>sensor_msgs</exec_depend><exec_depend>sensor_msgs_py</exec_depend>
<exec_depend>geometry_msgs</exec_depend><exec_depend>std_msgs</exec_depend>
<exec_depend>std_srvs</exec_depend><exec_depend>tf2_ros</exec_depend>
<exec_depend>ament_index_python</exec_depend><exec_depend>launch_ros</exec_depend>
<exec_depend>gouda_navigation</exec_depend>
<exec_depend>gouda_sensors</exec_depend>
<exec_depend>rviz2</exec_depend><exec_depend>adi_imu_tr_driver_ros2</exec_depend><exec_depend>hesai_ros_driver</exec_depend><exec_depend>python3-aiohttp</exec_depend>
<exec_depend>slam_toolbox</exec_depend><exec_depend>lifecycle_msgs</exec_depend><exec_depend>python3-yaml</exec_depend><exec_depend>kiss_icp</exec_depend>
<test_depend>python3-pytest</test_depend>
<export><build_type>ament_python</build_type></export></package>
